/**
 * In-memory "database" of seed data. This stands in for a backend;
 * the api-client reads from it. Nothing else should import this directly —
 * go through `api` so the data source can be swapped for a real API later.
 */
import type {
  Application,
  Company,
  Job,
  Testimonial,
  UserProfile,
} from "@/shared/types";

const companies: Record<string, Company> = {
  vercel: { name: "Vercel", logo: "▲", brand: "from-zinc-200 to-zinc-500", size: "201–500", industry: "Developer Tools" },
  linear: { name: "Linear", logo: "◣", brand: "from-violet-500 to-indigo-500", size: "51–200", industry: "Productivity" },
  stripe: { name: "Stripe", logo: "S", brand: "from-indigo-500 to-purple-500", size: "5000+", industry: "Fintech" },
  figma: { name: "Figma", logo: "✦", brand: "from-rose-500 to-orange-500", size: "1000–5000", industry: "Design" },
  notion: { name: "Notion", logo: "N", brand: "from-zinc-300 to-zinc-500", size: "201–500", industry: "Productivity" },
  ramp: { name: "Ramp", logo: "↗", brand: "from-amber-400 to-yellow-500", size: "501–1000", industry: "Fintech" },
  supabase: { name: "Supabase", logo: "⚡", brand: "from-emerald-400 to-green-600", size: "51–200", industry: "Developer Tools" },
  retool: { name: "Retool", logo: "▤", brand: "from-sky-400 to-blue-600", size: "201–500", industry: "Developer Tools" },
  perplexity: { name: "Perplexity", logo: "∞", brand: "from-teal-400 to-cyan-600", size: "51–200", industry: "AI" },
  vanta: { name: "Vanta", logo: "◈", brand: "from-fuchsia-500 to-pink-500", size: "201–500", industry: "Security" },
};

export const jobs: Job[] = [
  {
    id: "fe-vercel-001",
    title: "Senior Frontend Engineer",
    company: companies.vercel,
    location: "San Francisco, CA",
    workMode: "Remote",
    type: "Full-time",
    level: "Senior",
    salaryMin: 180000,
    salaryMax: 240000,
    matchScore: 96,
    tags: ["React", "Next.js", "TypeScript", "Edge"],
    description:
      "Build the dashboard that millions of developers use to ship the web. You'll own complex, performance-critical surfaces end to end and set the bar for frontend quality.",
    responsibilities: [
      "Architect and ship features across the Vercel dashboard",
      "Drive performance, accessibility, and DX improvements",
      "Partner with design to craft delightful, fast interfaces",
      "Mentor engineers and lead frontend architecture reviews",
    ],
    requirements: [
      "5+ years building production React applications",
      "Deep expertise in Next.js and the React rendering model",
      "Strong eye for UI detail, motion, and accessibility",
      "Experience with performance profiling and Core Web Vitals",
    ],
    perks: ["Fully remote", "Equity", "Top-tier hardware", "Unlimited PTO"],
    postedAt: "2026-06-10T09:00:00Z",
    applicants: 84,
    featured: true,
  },
  {
    id: "fe-linear-002",
    title: "Product Engineer, Frontend",
    company: companies.linear,
    location: "Remote (Global)",
    workMode: "Remote",
    type: "Full-time",
    level: "Mid",
    salaryMin: 150000,
    salaryMax: 200000,
    matchScore: 92,
    tags: ["TypeScript", "React", "Realtime", "GraphQL"],
    description:
      "Help build the tool that high-performing teams use to plan and ship. We obsess over speed, craft, and keyboard-first interactions.",
    responsibilities: [
      "Design and build polished, fast product features",
      "Optimize a realtime sync engine on the client",
      "Sweat the details of motion and micro-interactions",
    ],
    requirements: [
      "3+ years of frontend product engineering",
      "Fluency in TypeScript and modern React",
      "Care for performance and pixel-level polish",
    ],
    perks: ["Remote-first", "Equity", "Quarterly retreats", "Learning budget"],
    postedAt: "2026-06-09T12:00:00Z",
    applicants: 132,
    featured: true,
  },
  {
    id: "fe-stripe-003",
    title: "Frontend Engineer, Payments UI",
    company: companies.stripe,
    location: "New York, NY",
    workMode: "Hybrid",
    type: "Full-time",
    level: "Mid",
    salaryMin: 165000,
    salaryMax: 215000,
    matchScore: 88,
    tags: ["React", "TypeScript", "Design Systems"],
    description:
      "Build payment experiences trusted by millions of businesses. You'll work on reusable component systems that power Stripe's checkout and dashboard.",
    responsibilities: [
      "Develop and maintain Stripe's design system components",
      "Ship accessible, internationalized payment flows",
      "Collaborate across teams to keep UX consistent",
    ],
    requirements: [
      "3+ years frontend experience with React",
      "Experience building or consuming design systems",
      "Strong accessibility fundamentals (WCAG)",
    ],
    perks: ["Hybrid", "Equity", "Wellness stipend", "401k match"],
    postedAt: "2026-06-07T15:30:00Z",
    applicants: 210,
  },
  {
    id: "fe-figma-004",
    title: "Senior Engineer, Design Tools",
    company: companies.figma,
    location: "San Francisco, CA",
    workMode: "Hybrid",
    type: "Full-time",
    level: "Senior",
    salaryMin: 190000,
    salaryMax: 250000,
    matchScore: 84,
    tags: ["TypeScript", "Canvas", "WebGL", "Performance"],
    description:
      "Push the limits of what's possible in the browser. Work on the rendering and interaction systems behind Figma's collaborative canvas.",
    responsibilities: [
      "Build high-performance canvas and rendering features",
      "Profile and optimize for 60fps interactions",
      "Collaborate with design on novel interaction patterns",
    ],
    requirements: [
      "5+ years frontend with a performance focus",
      "Comfort with low-level rendering (Canvas/WebGL a plus)",
      "Systems thinking and strong CS fundamentals",
    ],
    perks: ["Hybrid", "Equity", "Catered meals", "Health & dental"],
    postedAt: "2026-06-05T10:00:00Z",
    applicants: 156,
  },
  {
    id: "fe-notion-005",
    title: "Frontend Engineer, Editor",
    company: companies.notion,
    location: "Remote (US)",
    workMode: "Remote",
    type: "Full-time",
    level: "Mid",
    salaryMin: 155000,
    salaryMax: 205000,
    matchScore: 81,
    tags: ["React", "TypeScript", "Editors", "Realtime"],
    description:
      "Build the block-based editor that powers millions of workspaces. Deep, rewarding frontend problems around text, drag-and-drop, and sync.",
    responsibilities: [
      "Develop editor features used by millions daily",
      "Solve hard problems in rich-text and DnD",
      "Improve editor performance and reliability",
    ],
    requirements: [
      "3+ years of complex frontend work",
      "Experience with rich-text or editor frameworks",
      "Strong product instincts",
    ],
    perks: ["Remote", "Equity", "Home office budget", "Generous PTO"],
    postedAt: "2026-06-04T08:00:00Z",
    applicants: 98,
  },
  {
    id: "fe-ramp-006",
    title: "Staff Frontend Engineer",
    company: companies.ramp,
    location: "New York, NY",
    workMode: "Hybrid",
    type: "Full-time",
    level: "Staff",
    salaryMin: 220000,
    salaryMax: 290000,
    matchScore: 79,
    tags: ["React", "TypeScript", "Architecture", "Leadership"],
    description:
      "Set the technical direction for Ramp's frontend. Lead architecture, mentor engineers, and ship finance tooling people love.",
    responsibilities: [
      "Own frontend architecture and standards",
      "Lead large cross-team initiatives",
      "Mentor and grow the engineering team",
    ],
    requirements: [
      "7+ years frontend, including technical leadership",
      "Track record of architecting large React apps",
      "Excellent communication and mentorship",
    ],
    perks: ["Hybrid", "Significant equity", "Health", "Commuter benefits"],
    postedAt: "2026-06-02T14:00:00Z",
    applicants: 64,
  },
  {
    id: "fe-supabase-007",
    title: "Frontend Engineer (OSS)",
    company: companies.supabase,
    location: "Remote (Global)",
    workMode: "Remote",
    type: "Full-time",
    level: "Mid",
    salaryMin: 140000,
    salaryMax: 190000,
    matchScore: 86,
    tags: ["React", "Next.js", "TypeScript", "Open Source"],
    description:
      "Work in the open on the dashboard and docs that developers use to build with Postgres. Your PRs ship to a huge community.",
    responsibilities: [
      "Build dashboard features in public",
      "Improve docs and developer onboarding",
      "Engage with the open-source community",
    ],
    requirements: [
      "3+ years React/Next.js",
      "Comfortable working asynchronously and in public",
      "Bonus: experience with Postgres or DX tooling",
    ],
    perks: ["Fully remote", "Equity", "Open-source culture", "Async-first"],
    postedAt: "2026-06-08T11:00:00Z",
    applicants: 145,
  },
  {
    id: "fe-retool-008",
    title: "Frontend Engineer, Platform",
    company: companies.retool,
    location: "San Francisco, CA",
    workMode: "On-site",
    type: "Full-time",
    level: "Mid",
    salaryMin: 160000,
    salaryMax: 210000,
    matchScore: 74,
    tags: ["React", "TypeScript", "Drag & Drop"],
    description:
      "Build the visual app builder that lets teams ship internal tools fast. Heavy drag-and-drop, state, and plugin systems.",
    responsibilities: [
      "Develop the drag-and-drop app canvas",
      "Build a robust component/plugin system",
      "Improve builder performance",
    ],
    requirements: [
      "3+ years React",
      "Experience with complex stateful UIs",
      "Interest in developer tooling",
    ],
    perks: ["On-site SF", "Equity", "Meals", "Health"],
    postedAt: "2026-05-30T09:00:00Z",
    applicants: 71,
  },
  {
    id: "fe-perplexity-009",
    title: "Frontend Engineer, AI Products",
    company: companies.perplexity,
    location: "Remote (US)",
    workMode: "Remote",
    type: "Full-time",
    level: "Senior",
    salaryMin: 185000,
    salaryMax: 245000,
    matchScore: 90,
    tags: ["React", "Next.js", "Streaming", "AI"],
    description:
      "Design the interfaces for answer engines used by millions. Streaming UIs, citations, and fast, trustworthy AI experiences.",
    responsibilities: [
      "Build streaming, real-time AI answer interfaces",
      "Craft trustworthy citation and source UX",
      "Optimize for latency and perceived performance",
    ],
    requirements: [
      "5+ years frontend with React/Next.js",
      "Experience with streaming/SSE UIs",
      "Strong product and design sensibility",
    ],
    perks: ["Remote", "Equity", "Frontier AI access", "Health"],
    postedAt: "2026-06-11T16:00:00Z",
    applicants: 188,
    featured: true,
  },
  {
    id: "fe-vanta-010",
    title: "Frontend Engineer, Compliance UX",
    company: companies.vanta,
    location: "Remote (US)",
    workMode: "Remote",
    type: "Full-time",
    level: "Mid",
    salaryMin: 150000,
    salaryMax: 195000,
    matchScore: 76,
    tags: ["React", "TypeScript", "Data Viz"],
    description:
      "Turn complex security compliance into clear, guided product experiences. Lots of data-dense dashboards and workflows.",
    responsibilities: [
      "Build data-rich compliance dashboards",
      "Design clear workflows for complex tasks",
      "Improve accessibility across the product",
    ],
    requirements: [
      "3+ years React/TypeScript",
      "Experience with data visualization",
      "Care for clarity in complex UIs",
    ],
    perks: ["Remote", "Equity", "Wellness stipend", "Health"],
    postedAt: "2026-06-01T13:00:00Z",
    applicants: 53,
  },
  {
    id: "fe-linear-011",
    title: "Frontend Engineer, Mobile Web",
    company: companies.linear,
    location: "Remote (Global)",
    workMode: "Remote",
    type: "Contract",
    level: "Mid",
    salaryMin: 130000,
    salaryMax: 170000,
    matchScore: 72,
    tags: ["React", "PWA", "Performance"],
    description:
      "Deliver a fast, native-feeling mobile web experience for Linear on a 6-month contract with extension potential.",
    responsibilities: [
      "Build responsive, touch-first interfaces",
      "Optimize bundle size and load performance",
      "Ensure parity with the desktop experience",
    ],
    requirements: [
      "3+ years frontend, mobile web focus",
      "Strong performance optimization skills",
      "Self-directed in a remote setting",
    ],
    perks: ["Remote", "Flexible hours", "Possible extension"],
    postedAt: "2026-05-28T10:00:00Z",
    applicants: 41,
  },
  {
    id: "fe-figma-012",
    title: "Frontend Intern, Summer 2026",
    company: companies.figma,
    location: "San Francisco, CA",
    workMode: "On-site",
    type: "Internship",
    level: "Junior",
    salaryMin: 9000,
    salaryMax: 11000,
    matchScore: 68,
    tags: ["React", "TypeScript", "Learning"],
    description:
      "A 12-week internship building real features alongside senior engineers. Mentorship, ownership, and impact from day one.",
    responsibilities: [
      "Ship a meaningful project end to end",
      "Pair with senior engineers and designers",
      "Learn production frontend practices",
    ],
    requirements: [
      "Currently pursuing a CS or related degree",
      "Solid JavaScript and some React",
      "Eagerness to learn and strong communication",
    ],
    perks: ["Paid (monthly)", "Housing stipend", "Mentorship", "Return offer potential"],
    postedAt: "2026-05-25T09:00:00Z",
    applicants: 320,
  },
];

export const applications: Application[] = [
  {
    id: "app-001",
    job: pickJob("fe-perplexity-009"),
    stage: "offer",
    appliedAt: "2026-05-20T09:00:00Z",
    nextStep: "Review offer letter by Jun 16",
    notes: "Strong team fit. Comp negotiation in progress.",
    timeline: [
      { label: "Applied", date: "2026-05-20T09:00:00Z" },
      { label: "Recruiter screen", date: "2026-05-23T09:00:00Z" },
      { label: "Technical interview", date: "2026-05-28T09:00:00Z" },
      { label: "Onsite loop", date: "2026-06-04T09:00:00Z" },
      { label: "Offer extended", date: "2026-06-10T09:00:00Z" },
    ],
  },
  {
    id: "app-002",
    job: pickJob("fe-vercel-001"),
    stage: "interview",
    appliedAt: "2026-06-01T09:00:00Z",
    nextStep: "System design round — Jun 14, 11:00 AM",
    notes: "Recruiter very responsive. Prep DS/system design.",
    timeline: [
      { label: "Applied", date: "2026-06-01T09:00:00Z" },
      { label: "Recruiter screen", date: "2026-06-05T09:00:00Z" },
      { label: "Technical interview", date: "2026-06-09T09:00:00Z" },
    ],
  },
  {
    id: "app-003",
    job: pickJob("fe-linear-002"),
    stage: "interview",
    appliedAt: "2026-06-02T09:00:00Z",
    nextStep: "Take-home review call — Jun 13",
    timeline: [
      { label: "Applied", date: "2026-06-02T09:00:00Z" },
      { label: "Recruiter screen", date: "2026-06-06T09:00:00Z" },
    ],
  },
  {
    id: "app-004",
    job: pickJob("fe-stripe-003"),
    stage: "applied",
    appliedAt: "2026-06-08T09:00:00Z",
    timeline: [{ label: "Applied", date: "2026-06-08T09:00:00Z" }],
  },
  {
    id: "app-005",
    job: pickJob("fe-supabase-007"),
    stage: "applied",
    appliedAt: "2026-06-09T09:00:00Z",
    notes: "Referred by a friend on the team.",
    timeline: [{ label: "Applied", date: "2026-06-09T09:00:00Z" }],
  },
  {
    id: "app-006",
    job: pickJob("fe-figma-004"),
    stage: "saved",
    appliedAt: "2026-06-11T09:00:00Z",
    nextStep: "Tailor resume before applying",
    timeline: [{ label: "Saved", date: "2026-06-11T09:00:00Z" }],
  },
  {
    id: "app-007",
    job: pickJob("fe-notion-005"),
    stage: "saved",
    appliedAt: "2026-06-11T12:00:00Z",
    timeline: [{ label: "Saved", date: "2026-06-11T12:00:00Z" }],
  },
  {
    id: "app-008",
    job: pickJob("fe-ramp-006"),
    stage: "rejected",
    appliedAt: "2026-05-18T09:00:00Z",
    notes: "Wanted more leadership scope. Good practice loop.",
    timeline: [
      { label: "Applied", date: "2026-05-18T09:00:00Z" },
      { label: "Recruiter screen", date: "2026-05-22T09:00:00Z" },
      { label: "Rejected", date: "2026-05-27T09:00:00Z" },
    ],
  },
  {
    id: "app-009",
    job: pickJob("fe-retool-008"),
    stage: "rejected",
    appliedAt: "2026-05-15T09:00:00Z",
    timeline: [
      { label: "Applied", date: "2026-05-15T09:00:00Z" },
      { label: "Rejected", date: "2026-05-21T09:00:00Z" },
    ],
  },
  {
    id: "app-010",
    job: pickJob("fe-vanta-010"),
    stage: "applied",
    appliedAt: "2026-06-10T09:00:00Z",
    timeline: [{ label: "Applied", date: "2026-06-10T09:00:00Z" }],
  },
];

export const user: UserProfile = {
  name: "Aria Sharma",
  title: "Senior Frontend Engineer",
  location: "Bengaluru, India",
  email: "aria.sharma@example.com",
  skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Accessibility", "Performance"],
  desiredRoles: ["Senior Frontend Engineer", "Product Engineer", "Frontend Architect"],
  profileStrength: 82,
};

export const testimonials: Testimonial[] = [
  {
    quote:
      "JobFlow's match scores were scary accurate. I stopped spraying applications and focused on the 90%+ roles — two offers in three weeks.",
    name: "Maya Rodriguez",
    role: "Senior Frontend Engineer",
  },
  {
    quote:
      "The tracker finally got my search out of a messy spreadsheet. Seeing every stage at a glance kept me sane during a stressful search.",
    name: "David Kim",
    role: "Full-stack Engineer",
  },
  {
    quote:
      "The AI cover letters sound like me, not a robot. I edit two lines and send. It's saved me probably 20 hours.",
    name: "Priya Nair",
    role: "Product Designer turned PM",
  },
  {
    quote:
      "Analytics showed me my response rate jumped when I tailored resumes. Data I never had before — game changer.",
    name: "Tom Becker",
    role: "Frontend Engineer",
  },
];

/** Build the trimmed Job snapshot stored on an Application. */
function pickJob(id: string): Application["job"] {
  const j = jobs.find((x) => x.id === id);
  if (!j) throw new Error(`Seed error: unknown job ${id}`);
  return {
    id: j.id,
    title: j.title,
    company: j.company,
    location: j.location,
    salaryMin: j.salaryMin,
    salaryMax: j.salaryMax,
    matchScore: j.matchScore,
  };
}
